Add Slack notifications for CI pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -184,7 +184,6 @@ jobs:
           gcp_service_account_key: ${{ secrets.GCP_KEY }}
           gcp_region: us-central1
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
   e2e:
     name: E2E Tests
     runs-on: ubuntu-latest
@@ -222,7 +221,7 @@ jobs:
     needs:
       - deploy-e2e
       - e2e
-    if: ${{ always() }}
+    if: always()
     steps:
       - name: Check out the repository
         uses: actions/checkout@v2
@@ -261,4 +260,99 @@ jobs:
           gcp_service_account_key: ${{ secrets.GCP_KEY }}
           gcp_region: us-central1
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
+  slack-notification:
+    name: Slack Notificaiton
+    runs-on: ubuntu-latest
+    needs:
+      - version
+      - frontend
+      - server
+      - build
+      - e2e
+      - deploy-acceptance
+    if: always()
+    steps:
+      - name: Create message
+        id: create-message
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          version=${{ needs.version.outputs.version }}
+          version_result=${{ needs.version.result }}
+          frontend_result=${{ needs.frontend.result }}
+          server_result=${{ needs.server.result }}
+          build_result=${{ needs.build.result }}
+          e2e_result=${{ needs.e2e.result }}
+          deploy_acceptance_result=${{ needs.deploy-acceptance.result }}
+
+          github_actions_run_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
+          message_file=$(mktemp -d)/message.txt
+          touch $message_file
+
+          function processIfMessage {
+            if [ -s $message_file ]
+            then
+              echo ::group::Setting message
+              echo "[View Run]($github_actions_run_url)" >> $message_file
+              message=$(cat $message_file)
+              echo Message is
+              echo $message
+              echo ::endgroup::
+
+              echo ::set-output name=message::$message
+              exit
+            fi
+          }
+
+          if [ $version_result != 'success' ]
+          then
+            echo "❌ Failed to create new version (job $version_result)." >> $message_file
+          fi
+
+          processIfMessage
+
+          if [ $frontend_result = 'success' ]
+          then
+            echo "✅ Twocan v$version frontend built." >> $message_file
+          else
+            echo "❌ Twocan v$version frontend $frontend_result." >> $message_file
+          fi
+
+          if [ $server_result = 'success' ]
+          then
+            echo "✅ Twocan v$version server built." >> $message_file
+          else
+            echo "❌ Twocan v$version server $frontend_result." >> $message_file
+          fi
+
+          if [ $build_result = 'success' ]
+          then
+            echo "✅ Twocan v$version build created." >> $message_file
+          else
+            echo "❌ Twocan v$version build $frontend_result." >> $message_file
+          fi
+
+          if [ $e2e_result = 'success' ]
+          then
+            echo "✅ Twocan v$version passed E2E tests." >> $message_file
+          else
+            echo "❌ Twocan v$version E2E tests $frontend_result." >> $message_file
+          fi
+
+          if [ $deploy_acceptance_result = 'success' ]
+          then
+            echo "🚀 Twocan v$version deployed to acceptance." >> $message_file
+          else
+            echo "❌ Twocan v$version deploy to acceptance $frontend_result." >> $message_file
+          fi
+
+          processIfMessage
+      - name: Slack
+        id: slack
+        uses: slackapi/slack-github-action@v1.16.0
+        with:
+          channel-id: '#test-notifications'
+          slack-message: ${{ steps.create-message.outputs.message }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
